// scans for lucide icon names and emits offline icon collections so neither the
// library nor the showcase ever fetches icon data from the iconify API at runtime.
// run with: npm run gen:icons
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { getIcons } from "@iconify/utils"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const lucide = JSON.parse(readFileSync(join(root, "node_modules/@iconify-json/lucide/icons.json"), "utf8"))

const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p, out)
    else if (/\.(vue|js)$/.test(name)) out.push(p)
  }
  return out
}

const namesIn = (dir) => {
  const found = new Set()
  for (const file of walk(dir)) {
    for (const m of readFileSync(file, "utf8").matchAll(/lucide:([a-z0-9-]+)/g)) found.add(m[1])
  }
  return [...found].sort()
}

const emit = (outPath, names, header) => {
  const collection = getIcons(lucide, names)
  const missing = names.filter((n) => !collection.icons[n] && !collection.aliases?.[n])
  if (missing.length) throw new Error(`icons not found in lucide set: ${missing.join(", ")}`)
  const body = [
    "// generated by scripts/gen-icons.mjs - do not edit by hand",
    `// ${header}`,
    'import { addCollection } from "@iconify/vue"',
    "",
    `addCollection(${JSON.stringify(collection, null, 2)})`,
    "",
  ].join("\n")
  writeFileSync(join(root, outPath), body)
  console.log(`${outPath}: ${names.length} icons`)
}

const srcNames = namesIn(join(root, "src"))
emit("src/icons.js", srcNames, "icons used by the components themselves, registered offline")

const storyNames = namesIn(join(root, "stories")).filter((n) => !srcNames.includes(n))
emit("stories/icons.js", storyNames, "icons used only by showcase stories, registered offline")
