// primitives
export { default as Button } from "./components/Button.vue"
export { default as Badge } from "./components/Badge.vue"
export { default as Card } from "./components/Card.vue"
export { default as Panel } from "./components/Panel.vue"
export { default as PanelSection } from "./components/PanelSection.vue"
export { default as EntityCard } from "./components/EntityCard.vue"
export { default as Stat } from "./components/Stat.vue"
export { default as Callout } from "./components/Callout.vue"
export { default as Banner } from "./components/Banner.vue"
export { default as Spinner } from "./components/Spinner.vue"
export { default as Skeleton } from "./components/Skeleton.vue"
export { default as ProgressBar } from "./components/ProgressBar.vue"
export { default as Avatar } from "./components/Avatar.vue"
export { default as Kbd } from "./components/Kbd.vue"
export { default as Divider } from "./components/Divider.vue"
export { default as ArrowLink } from "./components/ArrowLink.vue"
export { default as SectionLabel } from "./components/SectionLabel.vue"
export { default as FieldLabel } from "./components/FieldLabel.vue"
export { default as MonoLabel } from "./components/MonoLabel.vue"
export { default as Display } from "./components/Display.vue"
export { default as PastelBg } from "./components/PastelBg.vue"

// forms
export { default as Input } from "./components/Input.vue"
export { default as Textarea } from "./components/Textarea.vue"
export { default as Select } from "./components/Select.vue"
export { default as Checkbox } from "./components/Checkbox.vue"
export { default as Switch } from "./components/Switch.vue"
export { default as RadioGroup } from "./components/RadioGroup.vue"
export { default as Field } from "./components/Field.vue"
export { default as Combobox } from "./components/Combobox.vue"
export { default as TagInput } from "./components/TagInput.vue"
export { default as PinInput } from "./components/PinInput.vue"

// controls
export { default as NumberInput } from "./components/NumberInput.vue"
export { default as Scrubber } from "./components/Scrubber.vue"
export { default as ToggleGroup } from "./components/ToggleGroup.vue"
export { default as ToggleButton } from "./components/ToggleButton.vue"
export { default as Rating } from "./components/Rating.vue"
export { default as Knob } from "./components/Knob.vue"

// overlays
export { default as Tooltip } from "./components/Tooltip.vue"
export { default as Popover } from "./components/Popover.vue"
export { default as ConfirmPopover } from "./components/ConfirmPopover.vue"
export { default as Modal } from "./components/Modal.vue"
export { default as Drawer } from "./components/Drawer.vue"
export { default as DropdownMenu } from "./components/DropdownMenu.vue"
export { default as ContextMenu } from "./components/ContextMenu.vue"
export { default as Notifications } from "./components/Notifications.vue"

// data
export { default as Slider } from "./components/Slider.vue"
export { default as DatePicker } from "./components/DatePicker.vue"
export { default as DateRangePicker } from "./components/DateRangePicker.vue"
export { default as MultiSelect } from "./components/MultiSelect.vue"
export { default as Pagination } from "./components/Pagination.vue"
export { default as KeyValue } from "./components/KeyValue.vue"
export { default as Tree } from "./components/Tree.vue"
export { default as ActionList } from "./components/ActionList.vue"
export { default as ItemList } from "./components/ItemList.vue"
export { default as RecordList } from "./components/RecordList.vue"
export { default as ScrollArea } from "./components/ScrollArea.vue"
export { default as Accordion } from "./components/Accordion.vue"
export { default as Collapsible } from "./components/Collapsible.vue"
export { default as Breadcrumbs } from "./components/Breadcrumbs.vue"

// insight & data viz
export { default as Timeline } from "./components/Timeline.vue"
export { default as Sparkline } from "./components/Sparkline.vue"
export { default as Gauge } from "./components/Gauge.vue"
export { default as ActivityHeatmap } from "./components/ActivityHeatmap.vue"
export { default as DiffViewer } from "./components/DiffViewer.vue"
export { default as Redactor } from "./components/Redactor.vue"
export { default as CodeBlock } from "./components/CodeBlock.vue"
export { default as ImageCompare } from "./components/ImageCompare.vue"
export { default as DistributionBar } from "./components/DistributionBar.vue"
export { default as Annotator } from "./components/Annotator.vue"
export { default as ConfidenceMeter } from "./components/ConfidenceMeter.vue"
export { default as PipelineStatus } from "./components/PipelineStatus.vue"
export { default as EmbeddingMap } from "./components/EmbeddingMap.vue"
export { default as ChunkedDocument } from "./components/ChunkedDocument.vue"
export { default as RetrievedChunks } from "./components/RetrievedChunks.vue"
export { default as CitedAnswer } from "./components/CitedAnswer.vue"

// token & cost
export { default as CostBreakdown } from "./components/CostBreakdown.vue"
export { default as CostByModel } from "./components/CostByModel.vue"
export { default as CostProjection } from "./components/CostProjection.vue"
export { default as CostEstimator } from "./components/CostEstimator.vue"
export { DEFAULT_MODEL_PRICING, costOf, formatUSD, formatTokens } from "./pricing.js"
export { default as TokenView } from "./components/TokenView.vue"
export { tokenize } from "./tokenizer.js"
export { default as Conversation } from "./components/Conversation.vue"

// chat
export { default as ChatThread } from "./components/ChatThread.vue"
export { default as ChatScroller } from "./components/ChatScroller.vue"
export { default as ChatMessage } from "./components/ChatMessage.vue"
export { default as ChatComposer } from "./components/ChatComposer.vue"
export { default as PromptMenu } from "./components/PromptMenu.vue"
export { default as TypingIndicator } from "./components/TypingIndicator.vue"
export { default as ToolCall } from "./components/ToolCall.vue"

// evaluation suites
export { default as EvalSuite } from "./components/EvalSuite.vue"
export { default as EvalScorecard } from "./components/EvalScorecard.vue"
export { default as EvalComparison } from "./components/EvalComparison.vue"
export { default as EvalRubricScore } from "./components/EvalRubricScore.vue"
export { default as EvalAssertion } from "./components/EvalAssertion.vue"
export { default as EvalAssertionList } from "./components/EvalAssertionList.vue"

// layout & nav
export { default as Tabs } from "./components/Tabs.vue"
export { default as AppLayout } from "./components/AppLayout.vue"
export { default as ListDetail } from "./components/ListDetail.vue"
export { default as SideNav } from "./components/SideNav.vue"
export { default as TenantSwitcher } from "./components/TenantSwitcher.vue"
export { default as PageHeader } from "./components/PageHeader.vue"
export { default as Toolbar } from "./components/Toolbar.vue"
export { default as MenuBar } from "./components/MenuBar.vue"
export { default as Wizard } from "./components/Wizard.vue"
export { default as SearchInput } from "./components/SearchInput.vue"
export { default as SegmentedControl } from "./components/SegmentedControl.vue"
export { default as FilterChip } from "./components/FilterChip.vue"
export { default as EmptyState } from "./components/EmptyState.vue"
export { default as Table } from "./components/Table.vue"

// composables
export { useClickOutside } from "./composables/useClickOutside.js"
export { useSmoothStream, SMOOTH_STREAM_DEFAULTS } from "./composables/useSmoothStream.js"
export { useStickToBottom } from "./composables/useStickToBottom.js"
export { toast, dismissToast, clearToasts, toasts } from "./composables/toast.js"
